// Drizzle schema for the `course_app` Postgres schema.
//
// Mirrors docs/wiki/webapp-data-model.md exactly. The DB stores USER ACTIVITY ONLY — content ids
// are plain strings validated against the static manifest in app code. There are no content tables
// and no foreign keys to content (adr/2026-08-01-06).

import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgSchema,
  primaryKey,
  real,
  smallint,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

export const courseApp = pgSchema("course_app");

// --- identity (Auth.js Drizzle adapter shapes) -----------------------------

export const users = courseApp.table("users", {
  // Generated by Postgres, matching the documented DDL, so rows inserted outside the app
  // (seeds, manual fixes, a future migration) get ids the same way.
  id: text("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  name: text("name"),
  email: text("email").notNull().unique(),
  emailVerified: timestamp("email_verified", { withTimezone: true, mode: "date" }),
  image: text("image"),

  // --- access control (adr/2026-08-04-08) ---
  // Current state lives here so the per-request check is one indexed read; the audit trail lives
  // in access_events. Same split as derived completion vs completion_events.
  isAdmin: boolean("is_admin").notNull().default(false),
  /** Null means active. Set to offboard without deleting the user or their progress. */
  revokedAt: timestamp("revoked_at", { withTimezone: true, mode: "date" }),
});

/**
 * Append-only record of who changed whose access, and when. Never updated or deleted.
 *
 * `actor_id` is null for changes that did not come from a person — the env bootstrap admin, or a
 * seed. Kept separate from the flags on `users` so revoking and re-granting leaves a history
 * rather than overwriting one timestamp.
 */
export const accessEvents = courseApp.table(
  "access_events",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    action: text("action")
      .notNull()
      .$type<"granted_admin" | "revoked_admin" | "revoked_access" | "restored_access">(),
    /** Who did it. Null = system (env bootstrap). No cascade: keep history if the actor is removed. */
    actorId: text("actor_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    check(
      "access_events_action_check",
      sql`${t.action} IN ('granted_admin', 'revoked_admin', 'revoked_access', 'restored_access')`
    ),
    index("access_events_user_idx").on(t.userId, t.createdAt.desc()),
  ]
);

export const accounts = courseApp.table(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] })]
);

// Required by the adapter's type contract; unused under the JWT session strategy.
export const sessions = courseApp.table("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
});

// --- activity primitives ---------------------------------------------------

export const videoProgress = courseApp.table(
  "video_progress",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** MP4 basename, e.g. 'm1-02-how-llms-behave'. */
    videoId: text("video_id").notNull(),
    /** Last known position — where "resume" picks up. */
    positionSeconds: real("position_seconds").notNull().default(0),
    /** Monotonic high-water mark; only ever moves forward. Completion is derived from this. */
    maxPositionSeconds: real("max_position_seconds").notNull().default(0),
    durationSeconds: real("duration_seconds"),
    /** Set server-side once max/duration >= 0.9. */
    completedAt: timestamp("completed_at", { withTimezone: true, mode: "date" }),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.videoId] })]
);

/** Append-only. Every attempt is kept; the best one counts. */
export const quizAttempts = courseApp.table(
  "quiz_attempts",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** Manifest lesson key (the source file path). */
    articleKey: text("article_key").notNull(),
    /** Positional answer slots; a multi-select slot is a comma-joined set, e.g. ["B","C,D"]. */
    answers: jsonb("answers").notNull().$type<string[]>(),
    score: smallint("score").notNull(),
    total: smallint("total").notNull(),
    passed: boolean("passed").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [index("quiz_attempts_user_article_idx").on(t.userId, t.articleKey, t.createdAt.desc())]
);

/**
 * Free-form reveals and read view-only lessons. `item_key` is always a lesson key (the source file
 * path); which of the two a row means is decided by the lesson's requirements, not by the row.
 */
export const manualCompletions = courseApp.table(
  "manual_completions",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    itemKey: text("item_key").notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.itemKey] })]
);

/**
 * Append-only reporting log. Never updated, never deleted.
 * The UI always derives completion live; this exists for reporting/history only. The UNIQUE
 * constraint is what makes the append idempotent under concurrent writes.
 */
export const completionEvents = courseApp.table(
  "completion_events",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /**
     * 'lesson' | 'module'. 'section' is accepted by the CHECK but never written any more: the
     * table is append-only, so rows recorded before adr/2026-08-04-11 stay exactly as they were.
     */
    itemType: text("item_type").notNull().$type<"lesson" | "module">(),
    /** Lesson key (the source file path), or the module number as text. */
    itemId: text("item_id").notNull(),
    earnedAt: timestamp("earned_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [
    unique("completion_events_user_item_key").on(t.userId, t.itemType, t.itemId),
    check(
      "completion_events_item_type_check",
      sql`${t.itemType} IN ('lesson', 'module', 'section')`
    ),
  ]
);
