// Typed access to the generated, client-safe course manifest.
//
// Import this from server components only. The JSON is ~680 KB; pulling it into a client component
// would ship the whole course to the browser. Pages read it on the server and pass down just the
// lesson they render.
//
// Generated by scripts/generate-content.mjs — never hand-edit src/content/*.json.

import raw from "./manifest.json";
import type { Lesson, Manifest, ModuleRef } from "./types";

export const manifest = raw as unknown as Manifest;

/** Course order — the array is already sorted by the generator. Drives prev/next. */
export const orderedLessons: Lesson[] = manifest.lessons;

const lessonsBySlug = new Map<string, Lesson>(manifest.lessons.map((l) => [l.slug, l]));
const lessonsByKey = new Map<string, Lesson>(manifest.lessons.map((l) => [l.key, l]));

export function getLesson(slug: string): Lesson | undefined {
  return lessonsBySlug.get(slug);
}

/** By source path — the id the database stores. */
export function getLessonByKey(key: string): Lesson | undefined {
  return lessonsByKey.get(key);
}

export function getModule(module: number): ModuleRef | undefined {
  return manifest.modules.find((m) => m.module === module);
}

export function getModuleLessons(module: number): Lesson[] {
  return manifest.lessons.filter((l) => l.module === module);
}

/** Module lessons bucketed into their source-section headings, in course order. */
export function getModuleGroups(module: number): { title: string; lessons: Lesson[] }[] {
  const groups: { title: string; lessons: Lesson[] }[] = [];
  for (const lesson of getModuleLessons(module)) {
    let g = groups.find((x) => x.title === lesson.group);
    if (!g) groups.push((g = { title: lesson.group, lessons: [] }));
    g.lessons.push(lesson);
  }
  return groups;
}

export function adjacentLessons(slug: string): { prev?: Lesson; next?: Lesson } {
  const lesson = lessonsBySlug.get(slug);
  if (!lesson) return {};
  return { prev: orderedLessons[lesson.order - 1], next: orderedLessons[lesson.order + 1] };
}

/** Every video id the app is allowed to record progress against (main + debrief). */
export const validVideoIds: ReadonlySet<string> = new Set(
  manifest.lessons.flatMap((l) => (l.video ? [l.video.videoId] : []))
);

/** Lesson keys that can be graded — the only keys `/api/quiz/submit` may accept. */
export const gradeableLessonKeys: ReadonlySet<string> = new Set(
  manifest.lessons.filter((l) => l.assessment?.kind === "quiz").map((l) => l.key)
);

/** Lesson keys whose model answer can be revealed — the only keys `/api/assessment/reveal` accepts. */
export const freeformLessonKeys: ReadonlySet<string> = new Set(
  manifest.lessons.filter((l) => l.assessment?.kind === "freeform").map((l) => l.key)
);

/** Lessons completed by reading them — the only keys `/api/progress/complete` may accept. */
export const viewOnlyLessonKeys: ReadonlySet<string> = new Set(manifest.viewOnlyLessonKeys);

/** Public base URL for videos. R2 today, CloudFront on AWS-day — same code either way. */
export const videoBaseUrl = process.env.NEXT_PUBLIC_VIDEO_BASE_URL ?? "";

export function videoUrl(video: { path: string }): string {
  return `${videoBaseUrl.replace(/\/$/, "")}/${video.path}`;
}
