// Typed access to the generated, client-safe course manifest.
//
// Import this from server components only. The JSON is ~680 KB; pulling it into a client component
// would ship the whole course to the browser. Pages read it on the server and pass down just the
// section or article they render.
//
// Generated by scripts/generate-content.mjs — never hand-edit src/content/*.json.

import raw from "./manifest.json";
import type { Article, Manifest, ModuleRef, Section } from "./types";

export const manifest = raw as unknown as Manifest;

const sectionsById = new Map<string, Section>(manifest.sections.map((s) => [s.id, s]));

export function getSection(id: string): Section | undefined {
  return sectionsById.get(id);
}

export function getModule(module: number): ModuleRef | undefined {
  return manifest.modules.find((m) => m.module === module);
}

export function getModuleSections(module: number): Section[] {
  return manifest.sections.filter((s) => s.module === module);
}

/** Course order, used for prev/next navigation. */
export const orderedSections: Section[] = manifest.sections;

export function adjacentSections(id: string): { prev?: Section; next?: Section } {
  const i = orderedSections.findIndex((s) => s.id === id);
  if (i < 0) return {};
  return { prev: orderedSections[i - 1], next: orderedSections[i + 1] };
}

/** Every video id the app is allowed to record progress against (main + debrief). */
export const validVideoIds: ReadonlySet<string> = new Set(
  manifest.sections.flatMap((s) =>
    [s.video?.videoId, s.debriefVideo?.videoId].filter((v): v is string => !!v)
  )
);

const articlesByKey = new Map<string, { article: Article; section: Section }>(
  manifest.sections.flatMap((section) =>
    section.articles.map((article) => [article.key, { article, section }] as const)
  )
);

export function getArticle(key: string): { article: Article; section: Section } | undefined {
  return articlesByKey.get(key);
}

/** Article keys that can be graded — the only keys `/api/quiz/submit` may accept. */
export const gradeableArticleKeys: ReadonlySet<string> = new Set(
  manifest.sections.flatMap((s) =>
    s.articles.filter((a) => a.assessment?.kind === "quiz").map((a) => a.key)
  )
);

/** Article keys whose model answer can be revealed — the only keys `/api/assessment/reveal` accepts. */
export const freeformArticleKeys: ReadonlySet<string> = new Set(
  manifest.sections.flatMap((s) =>
    s.articles.filter((a) => a.assessment?.kind === "freeform").map((a) => a.key)
  )
);

/** Sections completable only by the explicit "Mark complete" button. */
export const zeroRequirementSections: ReadonlySet<string> = new Set(
  manifest.zeroRequirementSections
);

/** Public base URL for videos. R2 today, CloudFront on AWS-day — same code either way. */
export const videoBaseUrl = process.env.NEXT_PUBLIC_VIDEO_BASE_URL ?? "";

export function videoUrl(video: { path: string }): string {
  return `${videoBaseUrl.replace(/\/$/, "")}/${video.path}`;
}
